## 1 基本数据操作

In [97]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 1.3.1


### 1.1 创建PyTorch Tensor

In [98]:
x = torch.empty(5, 3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [99]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3300, 0.1686, 0.6637],
        [0.4694, 0.6479, 0.8125],
        [0.1262, 0.6053, 0.0463],
        [0.3959, 0.9953, 0.0712],
        [0.0091, 0.5611, 0.3800]])


指定数据类型：

In [100]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


从现有array创建：

In [101]:
x = torch.tensor([5.5, 3])
print(x)
y = torch.tensor([[5.2, 2], [1.2, 9]])
print(y)

tensor([5.5000, 3.0000])
tensor([[5.2000, 2.0000],
        [1.2000, 9.0000]])


从现有的tensor创建：

In [102]:
x = x.new_ones(5, 3)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.5636,  0.2672, -1.2523],
        [-0.7411, -0.0384,  0.3475],
        [-0.0169, -0.3022, -1.4429],
        [ 0.5407, -0.2323,  0.7721],
        [ 1.7933, -2.3761,  1.7563]])


获取tensor形状：

In [103]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


### 1.2 PyTorch Tensor操作

加法：

In [104]:
y = torch.rand(5, 3)
print(x+y)
print(torch.add(x, y))

# 输出复制给新的变量
z = torch.empty(5, 3)
print(z)
torch.add(x, y, out=z)
print(z)
z = x + y
print(z)

# inplace operate: add x to y
y.add_(x)
print(y)

tensor([[ 2.3121,  0.6403, -1.0691],
        [-0.4027,  0.0817,  0.5168],
        [ 0.9239,  0.0718, -0.5596],
        [ 1.4712,  0.0138,  1.3052],
        [ 2.2621, -1.4883,  2.0221]])
tensor([[ 2.3121,  0.6403, -1.0691],
        [-0.4027,  0.0817,  0.5168],
        [ 0.9239,  0.0718, -0.5596],
        [ 1.4712,  0.0138,  1.3052],
        [ 2.2621, -1.4883,  2.0221]])
tensor([[ 2.2969,  0.6403, -1.0691],
        [-0.4027,  0.0817,  0.5168],
        [ 0.9239,  0.0718, -0.5596],
        [ 1.4712,  0.0138,  1.3052],
        [ 2.2621, -1.4883,  2.0221]])
tensor([[ 2.3121,  0.6403, -1.0691],
        [-0.4027,  0.0817,  0.5168],
        [ 0.9239,  0.0718, -0.5596],
        [ 1.4712,  0.0138,  1.3052],
        [ 2.2621, -1.4883,  2.0221]])
tensor([[ 2.3121,  0.6403, -1.0691],
        [-0.4027,  0.0817,  0.5168],
        [ 0.9239,  0.0718, -0.5596],
        [ 1.4712,  0.0138,  1.3052],
        [ 2.2621, -1.4883,  2.0221]])
tensor([[ 2.3121,  0.6403, -1.0691],
        [-0.4027,  0.0817,  0.516

索引：

In [105]:
print(x)
print(x[4])
print(x[:, 0])

tensor([[ 1.5636,  0.2672, -1.2523],
        [-0.7411, -0.0384,  0.3475],
        [-0.0169, -0.3022, -1.4429],
        [ 0.5407, -0.2323,  0.7721],
        [ 1.7933, -2.3761,  1.7563]])
tensor([ 1.7933, -2.3761,  1.7563])
tensor([ 1.5636, -0.7411, -0.0169,  0.5407,  1.7933])


改变形状（内存共享）：

In [106]:
y = x.view(15)
print(y)
y = x.view(-1, 5)
print(y)

tensor([ 1.5636,  0.2672, -1.2523, -0.7411, -0.0384,  0.3475, -0.0169, -0.3022,
        -1.4429,  0.5407, -0.2323,  0.7721,  1.7933, -2.3761,  1.7563])
tensor([[ 1.5636,  0.2672, -1.2523, -0.7411, -0.0384],
        [ 0.3475, -0.0169, -0.3022, -1.4429,  0.5407],
        [-0.2323,  0.7721,  1.7933, -2.3761,  1.7563]])


In [107]:
x += 1
print(y)

tensor([[ 2.5636,  1.2672, -0.2523,  0.2589,  0.9616],
        [ 1.3475,  0.9831,  0.6978, -0.4429,  1.5407],
        [ 0.7677,  1.7721,  2.7933, -1.3761,  2.7563]])


改变形状并分配给拥有独立内存的变量:

In [108]:
y = x.clone().view(15)
x += 1
print(x)
print(y)

tensor([[ 3.5636,  2.2672,  0.7477],
        [ 1.2589,  1.9616,  2.3475],
        [ 1.9831,  1.6978,  0.5571],
        [ 2.5407,  1.7677,  2.7721],
        [ 3.7933, -0.3761,  3.7563]])
tensor([ 2.5636,  1.2672, -0.2523,  0.2589,  0.9616,  1.3475,  0.9831,  0.6978,
        -0.4429,  1.5407,  0.7677,  1.7721,  2.7933, -1.3761,  2.7563])


将一个标量tensor转换为一个number：

In [109]:
z = torch.randn(1)
print(z)
print(z.item())

tensor([0.2421])
0.2421070635318756


当两个tensor维度不同时，element-wise operate会触发广播机制：

In [110]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)

print(x + y)
# x --> [[1,2], [1,2], [1,2]]
# y --> [[1,1], [2,2], [3,3]]

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


关于是否共享内存的探讨（+=和inplace操作是共享内存的，一般的赋值运算则不共享内存）：

In [111]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
id_after = id(y)
print(id_before, id_after, id_before == id_after)

140255165048624 140255164751536 False


In [112]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y += x
id_after = id(y)
print(id_before == id_after)

True


In [113]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
id_after = id(y)
print(id_before == id_after)

True


In [114]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y.add_(x)
id_after = id(y)
print(id_before == id_after)

True


Tensor与numpy array之间的转换（from_numpy()：二者共享内存）：

In [115]:
a = torch.ones(5, 3)
b = a.numpy()
print(a, b, '\n')

a += 1
print(a, b, '\n')
b += 1
print(a, b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]) [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [116]:
import numpy as np
a = np.ones((5, 3))
b = torch.from_numpy(a)
print(a, '\n', b, '\n')

a += 1
print(a, '\n', b, '\n')
b += 1
print(a, '\n', b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) 

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 
 tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64) 

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)


使用tensor.tensor()不会共享内存：

In [117]:
c = torch.tensor(a)
print(a, '\n', c, '\n')

a += 1
print(a, '\n', c, '\n')
c += 1
print(a, '\n', c)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64) 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64) 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 
 tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64)


## 2 自动求梯度

### 2.1 相关概念
``tensor.requires_grad``若被设置为true，则该变量上的所有操作都将被追踪。通过调用``.backward``完成所有梯度计算。计算结果被存放到``.grad``属性中。

Tensor和Function共同构建了一个记录整个计算过程的非循环图。

In [142]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)
print(x)
# 直接通过数值创建x，不是任何变量的参数
print(x.grad_fn)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
None


In [143]:
y = x + 2
print(y)
# y是x的函数，有一个加法的grad_fn
print(y.grad_fn)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)


In [144]:
# is_leaf用来判断一个变量是否是计算图中的叶子结点（自变量）
print(x.is_leaf, y.is_leaf)

True False


In [145]:
z = 3 * y**2
o = z.mean()
print(z)
print(o)

tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
tensor(64.5000, grad_fn=<MeanBackward0>)


用inplace的方式改变变量的requires_grad属性：

In [138]:
a = torch.randn(2, 2)
b = (a * 3) / (a - 1)
print(a.requires_grad)
print(b.grad_fn)

a.requires_grad_(True)
b = (a * 3) / (a - 1)
print(b.grad_fn)

False
None


### 2.2 梯度计算（采用分母记法）
因为$o = \frac{1}{4} \sum_{i=1}^4 z_i = \frac{1}{4} \sum_{i=1}^4 3(x_i + 2)^2$，
所以$\frac{\partial o}{\partial x} \in \mathbb{R}^{(2 \times 2) \times 1} = \mathbb{R}^{2 \times 2}$，
梯度与自变量同形。且$\frac{\partial o}{\partial x_i} = \frac{3}{2} (x_i + 2)$。

因为$x_1 = 1$，所以$\frac{\partial o}{\partial x_1} = 4.5$；
因为$x_2 = 2$，所以$\frac{\partial o}{\partial x_1} = 6$。

In [146]:
# o是一个标量，无需指定要求导的变量（只有一个）。如果o是张量，要指定o中需要被求导的那个元素
o.backward()
print(x.grad)

tensor([[4.5000, 6.0000],
        [7.5000, 9.0000]])


梯度在反向传播的过程中是累加的。每运行一次反向传播，梯度都会累加之前的梯度。如果不想要这样，可以在执行反向传播之前将梯度清零。
$o_2 = \sum_{i=1}^4 x_i$，$\frac{\partial o_2}{\partial x_i} = x_i$。当$x_1 = 1$时，$o_2 = \sum_{i=1}^4 x_i = 1$。
这个结果累加上上一轮的[[4.5, 6.0], [7.5, 9.0]]，才是真正的输出。

In [147]:
o2 = x.sum()
o2.backward()
print(x.grad)

tensor([[ 5.5000,  7.0000],
        [ 8.5000, 10.0000]])


In [148]:
# 把梯度清零
o3 = x.sum()
x.grad.data.zero_()
o3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


为了简化反向传播，Torch仅允许**标量对张量**求导，不允许张量对张量求导。也就是说，因变量必须是一个标量。可是很多情况下因变量并不是张量，怎么办？

设$y = f(x)$是个张量，$w$是个和$y$同形的张量，则``y.backward(w)``的含义是$\frac{\partial l}{\partial x}$，
其中$l = \sum_{i} w_i y_i$。因此结果仍然是个与$x$同形的张量。

In [152]:
x = torch.tensor([1., 2., 3., 4.], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [154]:
w = torch.tensor([[1., 0.1], [0.01, 0.001]])
z.backward(w)

print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


如果中断梯度的跟踪，那么在后续的梯度计算中，被中断的变量不会参与进来。

In [161]:
x = torch.tensor(1., requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2
print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


下面的结果之所以是2是因为：$y_3 = y_1 + terminated(y_2) = y_1 = x^2$，
所以$\frac{\partial y_3}{\partial x} = 2 x$。

In [162]:
y3.backward()
print(x.grad)

tensor(2.)


在不影响后续梯度的计算的前提下，如何修改自变量的数值？直接对``tensor.data``属性进行操作。

In [163]:
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
