## 读取和存储

### 1.1 读写Tensor
使用pickle来``save``或``load``模型。

In [3]:
import torch
from torch import nn

Torch变量：

In [6]:
x = torch.ones(3)
torch.save(x, 'x.pt')

x2 = torch.load('x.pt')
print(x2)

tensor([1., 1., 1.])


列表：

In [7]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')

xy = torch.load('xy.pt')
print(xy)

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]


字典：

In [9]:
torch.save({'x': x, 'y': y}, 'xy_dict.pt')

xy2 = torch.load('xy_dict.pt')
print(xy2)

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}


### 1.2 读写模型

使用``stat_dict``获取模型中的参数。

In [11]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)
    
    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

net = MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.0332,  0.4242,  0.1681],
                      [-0.0659, -0.0359, -0.2049]])),
             ('hidden.bias', tensor([-0.3366,  0.5547])),
             ('output.weight', tensor([[-0.6760, -0.0151]])),
             ('output.bias', tensor([-0.1891]))])

In [12]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.01, momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.01,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [140608185714320,
    140608185714720,
    140608185712800,
    140608185712880]}]}

保存和加载模型参数：

In [15]:
torch.save(net.state_dict(), 'para_and_opt.pt')

In [17]:
model = MLP()
model.load_state_dict(torch.load('para_and_opt.pt'))
print(model)

MLP(
  (hidden): Linear(in_features=3, out_features=2, bias=True)
  (act): ReLU()
  (output): Linear(in_features=2, out_features=1, bias=True)
)


保存和加载整个模型：

In [18]:
torch.save(model, 'model.pt')

/Applications/anaconda3/envs/deep-learning/lib/python3.7/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type MLP. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/Applications/anaconda3/envs/deep-learning/lib/python3.7/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Linear. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/Applications/anaconda3/envs/deep-learning/lib/python3.7/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type ReLU. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


In [20]:
model = torch.load('model.pt')
print(model)

MLP(
  (hidden): Linear(in_features=3, out_features=2, bias=True)
  (act): ReLU()
  (output): Linear(in_features=2, out_features=1, bias=True)
)


In [21]:
net = MLP()
X = torch.randn(2, 3)
Y = net(X)
torch.save(net.state_dict(), 'net.pt')

net2 = MLP()
net2.load_state_dict(torch.load('net.pt'))
Y2 = net2(X)

Y == Y2

tensor([[True],
        [True]])